# Scraping
name: update Rt Estimates

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'


jobs: 
  update_rt:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages(c("here", "EpiEstim"))'
    # Run R script
    - name: Update RT Estimates Sintomi + CSV
      run: Rscript source/computeRt_sint.R
    # Run R script
    - name: Update RT Estimates Hospitalizations + CSV
      run: Rscript source/computeRt_hosp.R
    # Run R script
    - name: Update RT Estimates Lombardia + CSV
      run: Rscript source/computeRt_Lombardia.R
    # Run R script
    - name: Update RT Estimates RegioniPA_hosp + CSV
      run: Rscript source/computeRt_RegioniPA.R
    # Run R script
    - name: Update RT Estimates RegioniPA_sin + CSV
      run: Rscript source/computeRt_sint_RegioniPA.R
 

     
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
          echo "Checking data on: `date`"
          if [ -n "$(git status --porcelain)" ]; then
            echo "New update available"
            git config --local user.name actions-user
            git config --local user.email "actions@github.com"
            git add output/Rt_sint/* output/Rt_hosp/* output/regioneLombardia/* output/Rt_hosp_regionali/* output/Rt_sint_regionali/*
            git commit -am "Update data - $(date)"
            git push origin main
          else
            echo "no changes to commit"
          fi
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
        TZ: Europe/Rome
